### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by imns** [sungwoncho/node-producthunt#1]
When I try to run the example I get this error:

``` JS
  this.posts = require(`./api/v${this.version}/posts`)(this);
                       ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/natesmith/Sites/nodejs/product-hunt/app.js:1:84)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

It looks like you're doing some kind of string sub / templating, but I'm not sure what sort of magic you're using to achieve this.  

Could you update the readme with all the details needed to run the demo?

**Comment by sungwoncho** [comment]
You need to be running node v4 or higher. The demo in the README runs if you replace the comment with your credentials. Please re-open if using >v4 does not fix the issue.

**Comment by sungwoncho** [comment]
related to #2.
